### ISSUE TITLE
Bug: when we remove value from input NaN comes in Output Tag

### ISSUE THREAD

**Issue by ummeq** [atapas/html-tips-tricks#12]
Hello Tapas Adhikary,

I am not sure this is a valid bug or not. Please review the description.

Steps to reproduce.
1. On page load remove 0 from any of Input tag.
2. Equal sign gives  NaN, please find the attachment

When we remove any of value from Input NaN will come in Output tag
![image](https://user-images.githubusercontent.com/34029903/193868691-164a6946-61e6-4688-98fa-11cda44d29b8.png)

If its valid bug then please assign me.

**Comment by vinayak9303** [comment]
is this issue still open?

**Comment by ummeq** [comment]
I have pushed the changes waiting for PR review @vinayak9303
