### ISSUE TITLE
Adding checkbox and radio to Datalist tag

### ISSUE THREAD

**Issue by supminn** [atapas/html-tips-tricks#7]
Currently [Datalist](https://html5-tips.netlify.app/datalist/index.html) contains only drop down.
I would like to add an option of checkbox and radio options on this page.

**Comment by Sammydepoj** [comment]
Hi, I would like to work on this.
Kindly assign me

**Comment by Sammydepoj** [comment]
Okay then. 
thank you @supminn

**Comment by atapas** [comment]
Hi @supminn, the purpose of the data list is to have a native control which allows user to select from a set of element. The. checkbox and radio button do not fit in that demo. So it is an invalid feature request.

But don't worry. If you want to add a demo for checkbox and radio, please create separate one which should have an entry from the home page. Make sure to add any HTML 5 flavor to that. I am closing this one.
